
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame1.java
 *
 * Created on 23 Nov, 2013, 12:46:28 PM
 */

/**
 *
 * @author home
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /** Creates new form NewJFrame1 */
    public NewJFrame1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        li = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        rb1 = new javax.swing.JRadioButtonMenuItem();
        rb2 = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        rb3 = new javax.swing.JRadioButtonMenuItem();
        rb4 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        rb5 = new javax.swing.JRadioButtonMenuItem();
        rb6 = new javax.swing.JRadioButtonMenuItem();
        jMenu12 = new javax.swing.JMenu();
        rb7 = new javax.swing.JRadioButtonMenuItem();
        rb8 = new javax.swing.JRadioButtonMenuItem();
        jMenu19 = new javax.swing.JMenu();
        rb9 = new javax.swing.JRadioButtonMenuItem();
        rb10 = new javax.swing.JRadioButtonMenuItem();
        jMenu20 = new javax.swing.JMenu();
        rb11 = new javax.swing.JRadioButtonMenuItem();
        rb12 = new javax.swing.JRadioButtonMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        rb13 = new javax.swing.JRadioButtonMenuItem();
        rb14 = new javax.swing.JRadioButtonMenuItem();
        jMenu14 = new javax.swing.JMenu();
        rb15 = new javax.swing.JRadioButtonMenuItem();
        rb16 = new javax.swing.JRadioButtonMenuItem();
        jMenu29 = new javax.swing.JMenu();
        rb17 = new javax.swing.JRadioButtonMenuItem();
        rb18 = new javax.swing.JRadioButtonMenuItem();
        jMenu30 = new javax.swing.JMenu();
        rb19 = new javax.swing.JRadioButtonMenuItem();
        rb20 = new javax.swing.JRadioButtonMenuItem();
        jMenu6 = new javax.swing.JMenu();
        rb21 = new javax.swing.JRadioButtonMenuItem();
        rb22 = new javax.swing.JRadioButtonMenuItem();
        jMenu9 = new javax.swing.JMenu();
        rb23 = new javax.swing.JRadioButtonMenuItem();
        rb24 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VOTE");
        setMinimumSize(new java.awt.Dimension(590, 463));
        getContentPane().setLayout(null);

        li.setModel(new DefaultListModel());
        li.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(li);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 180, 210);

        jButton1.setText("Next Voter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(295, 200, 120, 23);

        jButton2.setText("Result Of Election");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 200, 140, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i21_18823923.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 640, 410);

        jMenu2.setText("School  Captain");

        buttonGroup1.add(rb1);
        rb1.setText("Boy");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        jMenu2.add(rb1);

        buttonGroup1.add(rb2);
        rb2.setText("Girl");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        jMenu2.add(rb2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("School Vice Captain");

        buttonGroup2.add(rb3);
        rb3.setText("Boy");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });
        jMenu3.add(rb3);

        buttonGroup2.add(rb4);
        rb4.setText("Girl");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });
        jMenu3.add(rb4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("House Captain");

        jMenu11.setText("Ajanta");

        buttonGroup3.add(rb5);
        rb5.setText("Boy");
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });
        jMenu11.add(rb5);

        buttonGroup3.add(rb6);
        rb6.setText("Girl");
        rb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6ActionPerformed(evt);
            }
        });
        jMenu11.add(rb6);

        jMenu4.add(jMenu11);

        jMenu12.setText("Nalanda");

        buttonGroup4.add(rb7);
        rb7.setText("Boy");
        rb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb7ActionPerformed(evt);
            }
        });
        jMenu12.add(rb7);

        buttonGroup4.add(rb8);
        rb8.setText("Girl");
        rb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb8ActionPerformed(evt);
            }
        });
        jMenu12.add(rb8);

        jMenu4.add(jMenu12);

        jMenu19.setText("Sanchi");

        buttonGroup5.add(rb9);
        rb9.setText("Boy");
        rb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb9ActionPerformed(evt);
            }
        });
        jMenu19.add(rb9);

        buttonGroup5.add(rb10);
        rb10.setText("Girl");
        rb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb10ActionPerformed(evt);
            }
        });
        jMenu19.add(rb10);

        jMenu4.add(jMenu19);

        jMenu20.setText("Takhshila");

        buttonGroup6.add(rb11);
        rb11.setText("Boy");
        rb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb11ActionPerformed(evt);
            }
        });
        jMenu20.add(rb11);

        buttonGroup6.add(rb12);
        rb12.setText("Girl");
        rb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb12ActionPerformed(evt);
            }
        });
        jMenu20.add(rb12);

        jMenu4.add(jMenu20);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("House Vice Captain");

        jMenu13.setText("Ajanta");

        buttonGroup7.add(rb13);
        rb13.setText("Boy");
        rb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb13ActionPerformed(evt);
            }
        });
        jMenu13.add(rb13);

        buttonGroup7.add(rb14);
        rb14.setText("Girl");
        rb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb14ActionPerformed(evt);
            }
        });
        jMenu13.add(rb14);

        jMenu5.add(jMenu13);

        jMenu14.setText("Nalanda");

        buttonGroup8.add(rb15);
        rb15.setText("Boy");
        rb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb15ActionPerformed(evt);
            }
        });
        jMenu14.add(rb15);

        buttonGroup8.add(rb16);
        rb16.setText("Girl");
        rb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb16ActionPerformed(evt);
            }
        });
        jMenu14.add(rb16);

        jMenu5.add(jMenu14);

        jMenu29.setText("Sanchi");

        buttonGroup9.add(rb17);
        rb17.setText("Boy");
        rb17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb17ActionPerformed(evt);
            }
        });
        jMenu29.add(rb17);

        buttonGroup9.add(rb18);
        rb18.setText("Girl");
        rb18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb18ActionPerformed(evt);
            }
        });
        jMenu29.add(rb18);

        jMenu5.add(jMenu29);

        jMenu30.setText("Takshila");

        buttonGroup10.add(rb19);
        rb19.setText("Boy");
        rb19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb19ActionPerformed(evt);
            }
        });
        jMenu30.add(rb19);

        buttonGroup10.add(rb20);
        rb20.setText("Girl");
        rb20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb20ActionPerformed(evt);
            }
        });
        jMenu30.add(rb20);

        jMenu5.add(jMenu30);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Cultural Captain");

        buttonGroup11.add(rb21);
        rb21.setText("Boy");
        rb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb21ActionPerformed(evt);
            }
        });
        jMenu6.add(rb21);

        buttonGroup11.add(rb22);
        rb22.setText("Girl");
        rb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb22ActionPerformed(evt);
            }
        });
        jMenu6.add(rb22);

        jMenuBar1.add(jMenu6);

        jMenu9.setText("Sports Captain");

        buttonGroup12.add(rb23);
        rb23.setText("Boy");
        rb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb23ActionPerformed(evt);
            }
        });
        jMenu9.add(rb23);

        buttonGroup12.add(rb24);
        rb24.setText("Girl");
        rb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb24ActionPerformed(evt);
            }
        });
        jMenu9.add(rb24);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();
    
        String q="select name from elecand  where post='SchoolCaptain' and gender='Male'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           
       }
       li.setModel(m);
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb1.setEnabled(false);


    }//GEN-LAST:event_rb1ActionPerformed

    private void liMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liMouseClicked
        // TODO add your handling code here:
        String n=(String) li.getSelectedValue();
         try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="update elecand  set counts = counts+1 where  name='"+n+"'";
        s.executeUpdate(q);

s.close();
con.close();
JOptionPane.showMessageDialog(null,"Your Vote Casted");
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        DefaultListModel m=(DefaultListModel)li.getModel();
        m.removeAllElements();

    }//GEN-LAST:event_liMouseClicked

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
          DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='SchoolCaptain' and gender='Female'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
          rb2.setEnabled(false);
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        // TODO add your handling code here:
         DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='SchoolViceCaptain' and gender='Male'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
                }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
         rb3.setEnabled(false);
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
        // TODO add your handling code here:
         DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='SchoolViceCaptain' and gender='Female'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();

          }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
         rb4.setEnabled(false);
    }//GEN-LAST:event_rb4ActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
        // TODO add your handling code here:
         DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseCaptain' and house='Ajanta' and gender='Male'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
                }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
         rb5.setEnabled(false);
    }//GEN-LAST:event_rb5ActionPerformed

    private void rb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6ActionPerformed
        // TODO add your handling code here
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseCaptain' and house='Ajanta' and gender='Female'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();

          }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb6.setEnabled(false);
    }//GEN-LAST:event_rb6ActionPerformed

    private void rb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb7ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseCaptain' and house='Nalanda' and gender='Male'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();

          }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb7.setEnabled(false);
    }//GEN-LAST:event_rb7ActionPerformed

    private void rb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb8ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseCaptain' and house='Nalanda' and gender='Female'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();

          }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
rb8.setEnabled(false);
    }//GEN-LAST:event_rb8ActionPerformed

    private void rb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb9ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseCaptain' and house='Sanchi' and gender='Male'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();

          }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb9.setEnabled(false);
    }//GEN-LAST:event_rb9ActionPerformed

    private void rb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb10ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseCaptain' and house='Sanchi' and gender='Female'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();

          }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb10.setEnabled(false);
    }//GEN-LAST:event_rb10ActionPerformed

    private void rb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb11ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseCaptain' and house='Takshila' and gender='Male'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
             }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb11.setEnabled(false);
    }//GEN-LAST:event_rb11ActionPerformed

    private void rb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb12ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseCaptain' and house='Takshila' and gender='Female'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb12.setEnabled(false);
    }//GEN-LAST:event_rb12ActionPerformed

    private void rb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb13ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseViceCaptain' and house='Ajanta' and gender='Male'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb13.setEnabled(false);
    }//GEN-LAST:event_rb13ActionPerformed

    private void rb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb14ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseViceCaptain' and house='Ajanta' and gender='Female'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb14.setEnabled(false);
    }//GEN-LAST:event_rb14ActionPerformed

    private void rb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb15ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseViceCaptain' and house='Nalanda' and gender='Male'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb15.setEnabled(false);
    }//GEN-LAST:event_rb15ActionPerformed

    private void rb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb16ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseViceCaptain' and house='Nalanda' and gender='Female'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb16.setEnabled(false);
    }//GEN-LAST:event_rb16ActionPerformed

    private void rb17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb17ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseViceCaptain' and house='Sanchi' and gender='Male'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb17.setEnabled(false);
    }//GEN-LAST:event_rb17ActionPerformed

    private void rb18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb18ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseViceCaptain' and house='Sanchi' and gender='Female'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb18.setEnabled(false);
    }//GEN-LAST:event_rb18ActionPerformed

    private void rb19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb19ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseViceCaptain' and house='Takshila' and gender='Male'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb19.setEnabled(false);
    }//GEN-LAST:event_rb19ActionPerformed

    private void rb20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb20ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='HouseViceCaptain' and house='Takshila' and gender='Female'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        rb20.setEnabled(false);
    }//GEN-LAST:event_rb20ActionPerformed

    private void rb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb21ActionPerformed
        // TODO add your handling code here:
         DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='CulturalCaptain' and gender='Male'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
         rb21.setEnabled(false);
    }//GEN-LAST:event_rb21ActionPerformed

    private void rb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb22ActionPerformed
        // TODO add your handling code here:
         DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='CulturalCaptain' and gender='Female'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
         rb22.setEnabled(false);
    }//GEN-LAST:event_rb22ActionPerformed

    private void rb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb23ActionPerformed
        // TODO add your handling code here:
         DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='SportsCaptain' and gender='Male'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
         rb23.setEnabled(false);
    }//GEN-LAST:event_rb23ActionPerformed

    private void rb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb24ActionPerformed
        // TODO add your handling code here:
         DefaultListModel m=(DefaultListModel)li.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select name from elecand  where post='SportsCaptain' and gender='Female'";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String n=r.getString(1);
           m.addElement(n);
           li.setModel(m);
       }
r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
         rb24.setEnabled(false);
    }//GEN-LAST:event_rb24ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        rb1.setEnabled(true);
        rb2.setEnabled(true);
        rb3.setEnabled(true);
        rb4.setEnabled(true);
        rb5.setEnabled(true);
        rb6.setEnabled(true);
        rb7.setEnabled(true);
        rb8.setEnabled(true);
        rb9.setEnabled(true);
        rb10.setEnabled(true);
        rb11.setEnabled(true);
        rb12.setEnabled(true);
        rb13.setEnabled(true);
        rb14.setEnabled(true);
        rb15.setEnabled(true);
        rb16.setEnabled(true);
        rb17.setEnabled(true);
        rb18.setEnabled(true);
        rb19.setEnabled(true);
        rb20.setEnabled(true);
        rb21.setEnabled(true);
        rb22.setEnabled(true);
        rb23.setEnabled(true);
        rb24.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new result().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList li;
    private javax.swing.JRadioButtonMenuItem rb1;
    private javax.swing.JRadioButtonMenuItem rb10;
    private javax.swing.JRadioButtonMenuItem rb11;
    private javax.swing.JRadioButtonMenuItem rb12;
    private javax.swing.JRadioButtonMenuItem rb13;
    private javax.swing.JRadioButtonMenuItem rb14;
    private javax.swing.JRadioButtonMenuItem rb15;
    private javax.swing.JRadioButtonMenuItem rb16;
    private javax.swing.JRadioButtonMenuItem rb17;
    private javax.swing.JRadioButtonMenuItem rb18;
    private javax.swing.JRadioButtonMenuItem rb19;
    private javax.swing.JRadioButtonMenuItem rb2;
    private javax.swing.JRadioButtonMenuItem rb20;
    private javax.swing.JRadioButtonMenuItem rb21;
    private javax.swing.JRadioButtonMenuItem rb22;
    private javax.swing.JRadioButtonMenuItem rb23;
    private javax.swing.JRadioButtonMenuItem rb24;
    private javax.swing.JRadioButtonMenuItem rb3;
    private javax.swing.JRadioButtonMenuItem rb4;
    private javax.swing.JRadioButtonMenuItem rb5;
    private javax.swing.JRadioButtonMenuItem rb6;
    private javax.swing.JRadioButtonMenuItem rb7;
    private javax.swing.JRadioButtonMenuItem rb8;
    private javax.swing.JRadioButtonMenuItem rb9;
    // End of variables declaration//GEN-END:variables

}
