
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * result.java
 *
 * Created on 23 Nov, 2013, 3:07:40 PM
 */

/**
 *
 * @author home
 */
public class result extends javax.swing.JFrame {

    /** Creates new form result */
    public result() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Result Declaration");
        setMinimumSize(new java.awt.Dimension(1050, 425));
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Lucida Sans Unicode", 3, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(l1);
        l1.setBounds(350, 10, 360, 40);

        ta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Post", "House", "Name", "Gender", "Votes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 60, 830, 240);

        jButton1.setText("Show  Winners");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 330, 130, 23);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(750, 330, 100, 23);

        jButton3.setText("Show Result");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 330, 130, 23);

        jButton4.setText("Next Election");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(530, 330, 130, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(910, 10, 120, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        l1.setText("Winners OF The Election");
    DefaultTableModel m=(DefaultTableModel)ta.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select post,house,name,gender,max(counts) from elecand order by post,gender";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String p=r.getString(1);
           String h=r.getString(2);
           String n=r.getString(3);
           String g=r.getString(4);
           int v=r.getInt(5);
           m.addRow(new Object[]{p,h,n,g,v});
           ta.setModel(m);
      }

r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        l1.setText("Result  Of  Election");
           DefaultTableModel m=(DefaultTableModel)ta.getModel();
          try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="select * from elecand";
       ResultSet r= s.executeQuery(q);
       for(int i=1;r.next();i++)
       {
           String p=r.getString(1);
           String h=r.getString(2);
           String n=r.getString(3);
           String g=r.getString(4);
           int v=r.getInt(5);
           m.addRow(new Object[]{p,h,n,g,v});
           ta.setModel(m);
      }

r.close();
s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here
         try{
       Class.forName("java.sql.Driver");
        String id = "root";
        String pw = "avs";
        String db = "jdbc:mysql://localhost/Project";
       Connection con=(Connection)DriverManager.getConnection(db,id,pw);
        Statement s=(Statement) con.createStatement();

        String q="delete from elecand  where gender not like '%le'";
        s.executeUpdate(q);

s.close();
con.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
         this.setVisible(false);
         new NewJFrame().setVisible(true);
         
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new result().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JTable ta;
    // End of variables declaration//GEN-END:variables

}
